### ISSUE TITLE
0.11 release

### ISSUE THREAD

**Issue by pieterv** [react-bootstrap/react-bootstrap#113]
Outstanding issues
- [X] ~~#111~~
- [x] ~~#106~~
- [X] ~~#104~~
- [x] ~~#112 - @pieterv to fix~~
- [X] ~~#115 - @stevoland to fix~~
- [X] ~~#117 - @pieterv to CR~~
- [X] ~~#122 - @pieterv to CR~~
- [x] ~~#120 (IE8 compatibility) - @stereosteve working on this~~

How does this look?

We should probably also create a version history file for new releases.
