### ISSUE TITLE
Improve Tabs API

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-bootstrap#1418]
I'm consolidating a number of other issues here:
- [ ] Support dropdowns in tabs (#100)
- [ ] Do not mount hidden tabs (#129)
- [x] Tab panel disappears when switching between tabs quickly (#557)
- [x] Setting `href` on tab headers (#1332)
- [x] Tabs with no initially selected tab and animation don't work (#1352)
- [x] Allow setting `className` on `<nav>` element (#1405)
- [x] Allow setting `className` on individual nav items (#1456)

**Comment by taion** [comment]
I think the way to go about this is to add a `Panes`/`Pane` pair of components, something that looks like:

```jsx
<Panes activeEventKey={2}>
  <Pane eventKey={1}>{content1}</Pane>
  <Pane eventKey={2}>{content2}</Pane>
  <Pane eventKey={3}>{content3}</Pane>
</Panes>
```

For the simple case, we can have `Tabs`/`Tab` (wondering if the old `TabbedArea`/`TabPane` names were better though...) wrap these components - probably even simplify it further by dropping the horizontal tabs support.

For the more complex cases with custom tabs, dropdowns, &c., just let users wire together a `Nav` and a `Panes` together themselves.

@jquense @mtscout6 This is a bit thematically similar to what you did with `Modal` and `Dropdown`. Do you think it'd be reasonable here?

**Comment by jquense** [comment]
we already have Tab, which I assume maps to Pane above...I assume Panes is sort of some incrementally helpful thing between wiring a bunch of Tab's to a Nav, and using the `Tabs` component? I like that approach i think, the current api is pretty hands off in an unhelpful way, this seems like a good middle ground, I with naming wasn't so hard...renaming anything in tab API would suck since we already did that fairly recently

**Comment by taion** [comment]
Yup that's the idea - so in the more complex scenarios you render a component with a `Nav` and a `Panes`, something like:

```jsx
onSelect = (e, eventKey) => {
  this.setState({activeEventKey: eventKey});
};

render() {
  const {activeEventKey} = this.state;

  return (
    <div>
      <Nav activeEventKey={activeEventKey} onSelect={this.onSelect}>
        {this.renderNavItems()}
      </Nav>
      <Panes activeEventKey={activeEventKey}>
        {this.renderPanes()}
      </Panes>
    </div>
  );
}
```

And then gut the current `Tabs` component and leave it as just a convenience thing for the original "vertical" tabs thing. I increasingly dislike the stuff I added for horizontal tabs and would prefer to get rid of it all.

**Comment by jquense** [comment]
I like it. It may be worth taking account of how much other stuff `<Tabs/>` adds aside from syncing the active pane and nav items. I recall there being a bunch of a11y stuff...I'd be good to offer that stuff here, but that may require some sort of parent component like Dropdown, Toggle, and Menu...which doesn't strike me as a great fit here.

**Comment by taion** [comment]
Yeah... that's tough. I wonder if we can't offer helpers of some sort.

**Comment by Someguy123** [comment]
+1 for tab improvements.

I'm currently working on an application, where the design involves the tabs being in a differently styled heading, and the content being in a container separated from those. The current Tab system doesn't really let me do this because it always renders the tab content immediately after the tabs, and I'm having to debate different solutions just to get this to look correct.

Would be great to see the `Panes` system implemented.

**Comment by bjwyse** [comment]
The tabs disappearing issue (https://github.com/react-bootstrap/react-bootstrap/issues/557) is related to animation. It can be reproduced on http://react-bootstrap.github.io/components.html#tabs-uncontrolled by using the left and right arrows to rapidly change tabs.

If the active tab changes while animation is still in progress then the animate end function never gets called, leaving previousActiveKey permanently set. (https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Tabs.js#L151)

Workaround is to disable animation on tabs.

**Comment by z-ax** [comment]
Is it possible to easily use slide animation for tabs on switch?

**Comment by taion** [comment]
Largely resolved by https://github.com/react-bootstrap/react-bootstrap/pull/1607.

**Comment by abobwhite** [comment]
I am having an issue in my implementation where the existence of the ```href``` attribute within the anchor tag in the ```Tab``` causes the default anchor tag behavior (changing the hash in the URL) which causes issues later (i.e. refresh). Either we need to be able to ```stopPropagation``` or to remove the ```href``` completely.

**Comment by taion** [comment]
That's doable with the new API.

**Comment by abobwhite** [comment]
@taion Is this new API available? I just pulled this down from the CDN yesterday (0.28.2). My client doesn't use npm or bower just yet so if this is cutting edge from master not yet on the CDN, let me know.

**Comment by taion** [comment]
It's merged but not released.

**Comment by abobwhite** [comment]
@taion I've pulled down the latest code but I keep getting an error on this line:
```var currentKeyIsStillValid = this.panes.indexOf(currentActiveKey) !== -1;``` in ```TabContent``` every time I try to create a new tab. I'm using ```<Tabs>``` containing ```<Tab>```s. The error indicates that ```this.panes``` is undefined.

**Comment by taion** [comment]
Given #1607, I'm going to close this mega-issue that tracks a huge list of changes, and re-open the unresolved sub-issues.

**Comment by Shadowman4205** [comment]
So how add link to tab?
i tried this on Tab.Container 
<NavItem  href="https://www.google.com" eventKey="Google">
                                        Google
</NavItem>

But nothing happened!

**Comment by enzious** [comment]
To get href to work when onSelect is set on Tab.Container, do this:

`<NavItem onSelect={false} href="https://www.google.com" eventKey="Google">Google</NavItem>`
