### ISSUE TITLE
DropdownButtons need an overhaul. 

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#526]
I know there are a lot of problems with the DropdownButton, which I hope to remedy soon. I know I'll have some time to work on them next week, but I can't guarantee a delivery date. I'm mainly creating this issue to aggregate all the dropdown issues in one place.

- #195 
- #230 
- #243 
- #250 
- #253 
- #299 
- #303 
- #368 
- #398 
- #411 
- #421 
- #456 
- #458 
- #470 
- #100 
- #486
- #522
- #629

Notes as per W3C WAI-ARIA Spec:

- [ ] When presenting the menu, ensure that it is completely visible on screen.
- Keyboard navigation. Should resolve #588
  - [x] Space or Enter - With focus on the button pressing Space or Enter will toggle the display of the drop-down menu. Focus remains on the button.
  - Down Arrow
    - [x] With focus on the button and no drop-down menu displayed, pressing Down Arrow will open the drop-down menu and move focus into the menu and onto the first menu item.
    - [x] With focus on the button and the drop-down menu open, pressing Down Arrow will move focus into the menu onto the first menu item.
  - Up and Down Arrow
    - [x] With focus on the drop-down menu, the Up and Down Arrow keys move focus within the menu items, "wrapping" at the top and bottom.
  - Escape
    - [x] With focus on the drop-down menu, pressing Escape closes the menu and returns focus to the button. Resolves #486 
  - Tab
    - [x] With focus on the button pressing the Tab key will take the user to the next tab focusable item on the page.
    - [x] With focus on the drop-down menu, pressing the Tab key will take the user to the next tab focusable item on the page. Note that this may be difficult to achieve on a web page.
    - [ ] Typing a letter (printable character) key moves focus to the next instance of a visible node whose title begins with that printable letter.
- [x] ~~The menu button itself has a role of button.~~ It is a button so not needed.
- [x] The menu button has an aria-haspopup property, set to true.
- [ ] Auto-generate an ID if one is not provided.
  - [ ] Ensure that id does not break server -> client rendering (See: facebook/react#4000)

Notes per reported issues:

- [x] Honor event handling api discussed in #419. Should resolve problem with:
  - #195
  - #243
  - #250
  - #368
  - #411
  - #456
  - #522 
  - #541 
  - #573 
  - #678
- [x] Allow custom className to DropdownMenu. Should resolve #230, #253, related to #595 
- [x] Allow open/closed state to be managed through props. Should resolve #303
- ~~Allow a Dropdown within a Dropdown. Should resolve #398~~ Not supported in Bootstrap 3. See: twbs/bootstrap#6342
- [x] Dropdown should work within a collapsed `Navbar`. Should resolve #421, and #700
- [x] Allow Custom Dropdown Menus aside from the default `DropdownMenu`. Should resolve #470 (Still in discussion)
- [ ] Allow to work with tabs. Should resolve #100 
  - Looks like this is dependent on a number of components updating their `onSelect` event signatures per #419. This will not likely land in the first release of the dropdown re-write. Sorry @mathieumg it will come at some point though.
- [ ] Allow option to open on hover. Should resolve #568 
  - [ ] Add documentation that it would not be good for accessibility standards.
- [x] Close when clicking outside component. Should resolve #615 
- [x] `MenuItem` has `disabled` prop. Resolves #246, and #606 
- [ ] passing the props `download`, `media`, `ping`, `rel`, `type` etc (applicable for `<a>`) down to `anchor` #629

Existing features that should still be supported:

- [x] `pullRight`
- [x] `dropup`
- [x] `noCaret`
- [x] DropdownButton `onClick` event handler
- [x] `bsSize`
- [x] `bsStyle`

Issues I Need to dig into more to understand completely:

- #299 
- #458

twbs/bootstrap#15263 - for reference. (Applies some Aria roles I hadn't considered up till now)

**Comment by manveru** [comment]
I'm not sure if there's a bug for this yet, but nesting dropdowns results in really broken menus.

**Comment by mtscout6** [comment]
Thanks @manveru I will take that into consideration.

**Comment by mtscout6** [comment]
For those of you following this issue, I have started on this though I don't have anything of note to push yet. I should get a little bit more time this week to work on this issue.

**Comment by mtscout6** [comment]
@manveru Support for sub menus was dropped in Bootstrap 3 so I don't think we will be including it here. So, you'll need to have your own custom component to do this. There is a good [solution](http://stackoverflow.com/questions/18023493/bootstrap-3-dropdown-sub-menu-missing#answer-18024991) proposed on StackOverflow. 

I am thinking about allowing for a `CustomDropdownMenu` as outlined in #470, which would be a great extensibility point for you to add this feature to your project. I'm still fleshing that out though so hopefully that ends up working out.

**Comment by mtscout6** [comment]
createChainedFunction cleanup: [From @jtenner on gitter](https://gitter.im/react-bootstrap/react-bootstrap?at=557b1050b62c8de7435cb430)

**Comment by mtscout6** [comment]
Suggestions by @rgrwkmn in https://github.com/react-bootstrap/react-bootstrap/pull/817#issuecomment-111587004

@mtscout6 I checked out your changes and updated my example in the docs just to see how it works. Using onClick, onRequestClose, and onSelect I can keep a my component and the DropdownButton in sync.

Some suggestions on semantics:

I had to look at the source to know what onClick meant whereas if it was called onToggle I'd know right away.

Seems to me it should be either onRequestToggle and onRequestClose or onToggle and onClose since when you're controlling the component they do the same thing. Maybe internally the naming makes more sense as is.

It might make sense to have a single callback like onOpenChange that passes a boolean as the only argument to indicate whether the internals of DropdownButton are trying to open or close the dropdown.

I merged your changes into my branch and committed my example so you can check it out.

**Comment by Plummat** [comment]
Hey! Is there a way to set the dropdown menu default to open under a dropdown button? thanks!

**Comment by mtscout6** [comment]
Can you explain that a little more, I don't quite follow what you are asking for.

**Comment by Plummat** [comment]
Sorry - is it possible to make a dropdown menu and and set it to open on render - ie, have the dropdown render in an opened state

**Comment by mtscout6** [comment]
>  Allow open/closed state to be managed through props. Should resolve #303

Yes that will be acheivable via props. Probably won't land until v0.24.0 though.

**Comment by AlexKVal** [comment]
I propose to assign you in all those issues so people can see that those issues are 'in the proccess'.
I can do it if you approve.

**Comment by mtscout6** [comment]
Fine with me.

**Comment by AlexKVal** [comment]
Done. 
BTW: There are already a handful of them closed :+1: :sparkle:

**Comment by AlexKVal** [comment]
I've edited the first message:
- Added #629 to the list of issues
- Added to the `Notes per reported issues:` `passing the props download, media, ping, rel, type etc (applicable for <a>) down to anchor #629`

**Comment by MatthewHerbst** [comment]
Can you please clarify if this is taking into account the root cause of #368 ?

I currently have the following React render call for my Nav component:

```javascript
render: function () {
    var projectMenuItemLinks = this.state.projects.map(function(project, i) {
      return (
        <MenuItemLink
          key={i}
          eventKey={'\'' + (i + 1) + '\''}
          to='validate'
          params={{projectId: project.id}}
        >
          {project.name}
        </MenuItemLink>
      );
    });

    return (
      <Navbar brand='Chegg Data Validation Tool' inverse toggleNavKey={0}>
        <Nav right eventKey={0}> {}
          <NavItemLink eventKey={1} to='home' params={{}}>Home</NavItemLink>
          <DropdownButton eventKey={2} title='Projects'>
            {projectMenuItemLinks}
          </DropdownButton>
          <NavItemLink eventKey={3} to='leaderboard' params={{}}>Leaderboard</NavItemLink>
          <NavItemLink eventKey={4} to='profile' params={{}}>Profile</NavItemLink>
        </Nav>
      </Navbar>
    );
  }
```

This is using `react-bootstrap` for everything except the `MenuItemLink` which is a wrapper around `MenuItem` created by `react-router-boostrap`.

When selecting one of the links from the dropdown, I would like the dropdown to close (in addition to the page navigation). Do/will I need to specify an `onSelect` as was being discussed in #368?

**Comment by mtscout6** [comment]
@MatthewHerbst yes the changes in the dropdown-revisited branch which is PR #1096 should fix the underlying problem. Though we are investigating an alternative approach that will be easier to work with. So, once #1096 is merged we'll need to update the react-router-bootstrap project to fix the problem you're describing.

**Comment by MatthewHerbst** [comment]
@mtscout6 awesome, thanks for the update!
