### ISSUE TITLE
Consider implementing simple components

### ISSUE THREAD

**Issue by stevoland** [react-bootstrap/react-bootstrap#56]
There's a lot of components with no interactivity that would just be wrappers around DOM elements with certain class names: badge, label, well, icon etc.

Should we add these? I'm in 2 minds, it adds a level of abstraction that might be useful if the classes change but creates another, albeit simple, API to learn.

Any comments?

__EDIT:__

In summation of current state:

- [x] Badge
- [x] Label
- [x] Well
- [x] Icon
- [x] Media
- [x] Thumbnail (See #488)
- [x] Breadcrumb (See #1273 and #1354)
- [x] Pager
- [x] Pagination (See #22 PR #786)
- [x] Responsive Embed (See #1359)
- [x] Images (See #1293)
- [x] Affix (See #200)

**Comment by mtscout6** [comment]
In summation of current state:

- [x] Badge
- [x] Label
- [x] Well
- [x] Icon
- [ ] Media
- [ ] Thumbnail
- [ ] Breadcrumb
- [x] Pager
- [ ] Pagination (See #22)

**Comment by JordanTheriault** [comment]
I'd like to do the Thumbnail if that's okay. I'm new to this repo but would love to get involved @mtscout6

**Comment by mtscout6** [comment]
@JordanTheriault That'd be great!

**Comment by ivan-kleshnin** [comment]
@mathieumg media is the worst Bootstrap part ever. It's totally broken in responsive aspect. 
Not recommend.

**Comment by dozoisch** [comment]
@mtscout6  Do we add embeds? http://getbootstrap.com/components/#responsive-embed

**Comment by mtscout6** [comment]
Both of those seem reasonable.

**Comment by dozoisch** [comment]
should add affix to the list

https://github.com/react-bootstrap/react-bootstrap/issues/200

**Comment by dozoisch** [comment]
#488 resolves thumbnails

**Comment by AlexKVal** [comment]
/cc @react-bootstrap/collaborators
Do we really want this issue as a condition for the `Milestone 1.0.0` ?

In my opinion if nobody is interested in those additional components,
so there is no value to make them.

And Steve named topic as 'Consider..', i.e. it doesn't mean that they 'must' be implemented.

I propose to remove it from the `Milestone 1.0.0`. :cherries:

**Comment by mathieumg** [comment]
I think they should be in 1.0, otherwise 1.0 wouldn't be 1.0. To me, 1.0 means "some stability" and "feature parity with Bootstrap". There is a need with regards to these components, but the implementation of some of them brings no challenge (or even benefits per se) to the table, probably a reason why they've been overlooked. Once we set to implement them, it shouldn't be too long, for most anyway.

**Comment by AlexKVal** [comment]
Then to all:
Pull requests are welcome :wink:

**Comment by dozoisch** [comment]
yeah I have the same opinion as @mathieumg on this. 1.0 should mean parity.

**Comment by deerawan** [comment]
Hi @dozoisch @mtscout6  I'm interested to help with images component. I'm working on it.

**Comment by dozoisch** [comment]
@deerawan awesome!

**Comment by AlexKVal** [comment]
And.. here we are :smile: Just a `Media` component left
<img width="320" alt="screen shot 2015-10-04 at 4 23 21 pm" src="https://cloud.githubusercontent.com/assets/847572/10268026/4df48ec4-6ab4-11e5-8eb0-5f0586345bd8.png">

though the comment about it:
> @mathieumg media is the worst Bootstrap part ever. It's totally broken in responsive aspect. 
Not recommend.

https://github.com/react-bootstrap/react-bootstrap/issues/56#issuecomment-92719944

**Comment by mathieumg** [comment]
It shouldn't be hard to implement, even though we know it's getting taken out of Bootstrap 4.

**Comment by dozoisch** [comment]
If it's getting taken out of BS4, I would just ignore it.

**Comment by taion** [comment]
Media is not getting taken out of BS4: http://v4-alpha.getbootstrap.com/layout/media-object/

**Comment by dozoisch** [comment]
Guess it makes sense to add it then!

**Comment by taion** [comment]
sadface

**Comment by alphashuro** [comment]
Why hasn't media been added yet? I think I'll give it a go

**Comment by taion** [comment]
I'd appreciate that. Thanks.

**Comment by alphashuro** [comment]
Why is there a completely misleading "Media content" section in the docs? I think that the elements in there deserve their own sections in the nav, and that "Media content/objects" should have the actual media objects. Can I fix this as well?

**Comment by taion** [comment]
They're for various sorts of media – carousels, responsive embeds, &c. That is the relevant category.

**Comment by alphashuro** [comment]
Other than the fact that it makes the documentation inconsistent with bootstrap's documentation, this leaves media objects with no section. unless I either create a new section or add them at the bottom of the Media content section, which would you suggest>

**Comment by taion** [comment]
They should go into that top-level "media" section.

**Comment by alphashuro** [comment]
Done #1707

**Comment by alphashuro** [comment]
I suppose that means this issue is done then?

**Comment by taion** [comment]
Thanks @alphashuro!
