### ISSUE TITLE
Should we explicitly define boolean defaults for documentation ?

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#976]
Edited (13 aug 2015):
- [x] Explicitly set defaults for boolean properties for the sake of documentation #1155
- [x] `NavBar`'s `navExpanded`-property is not so straightforward. It needs additional PR. https://github.com/react-bootstrap/react-bootstrap/issues/976#issuecomment-131048858
- [x] The same for `Panel` properties. It needs additional PR. #1161
- [x] `TabPane` and `TabbedArea` is renamed in `0.25`, then create PR for them against `v0.25-rc` branch #1160

--
https://github.com/react-bootstrap/react-bootstrap/pull/962#issuecomment-120647588

I can take a look through all components and add boolean defaults explicitly.
But before we should agree on this.

What do you think about it guys ?
/cc @react-bootstrap/collaborators

**Comment by mathieumg** [comment]
As discussed in that thread, I think the documentation generator should be the one setting the default when there's none in the code. Perhaps it could say "off" with something explaining, somewhere in the doc, that "off" means a default value of `undefined`.

**Comment by aabenoja** [comment]
> A potential problem with filling in a default of e.g. `false` is that code could potentially do something different for a `null`-y value than for a `false`-y one. I think it'd be stupid and broken to do that, but eh. Or I could be wrong - maybe better to require explicit defaults for boolean fields?

@taion I agree, that is stupid and broken. Should handling a `null` on a `bool` prop separately be a practice we should adopt? I see it's uses, just not in this project.

**Comment by taion** [comment]
@aabenoja I'm not saying that we do - and I hope we don't - but it is a small difference that's technically present between "no default" and "default is false".

**Comment by aabenoja** [comment]
A critical difference, yes, but a practice we should avoid. I think that convolutes what a bool prop should mean (at least, for our API).

**Comment by taion** [comment]
I think we should explicitly default all of these to `false`, just for the sake of clarity in documentation.

**Comment by AlexKVal** [comment]
Then I presume I can do this chore job if nobody already is doing it ?

**Comment by mtscout6** [comment]
I see nobody assigned to the issue :wink: If you assign yourself then that sounds like it's yours :smile:

**Comment by AlexKVal** [comment]
OK then I'm on it :smile:

**Comment by AlexKVal** [comment]
I've updated the first message.

--
`NavBar's` `navExpanded`-property is not so straightforward. It needs more concideration.

The same for `Panel` properties. It is also needs additional PR.

`TabPane` and `TabbedArea` is renamev in 0.25.
To ease future branches merging  I'll create PR for them against v0.25-rc branch.

**Comment by AlexKVal** [comment]
As for `NavBar's` `navExpanded` property.
It cannot be `false` by default because of 
```js
isNavExpanded() {
  return this.props.navExpanded != null ? this.props.navExpanded : this.state.navExpanded;
},
```
[src/Navbar.js#L73](https://github.com/react-bootstrap/react-bootstrap/blob/c7e3f07cf992067437cf9e020e8d3869bf64c36a/src/Navbar.js#L73)

Then what to do ? Leave it as is ?

**Comment by taion** [comment]
For e.g. `navExpanded` we should just use `uncontrollable` or something similar, per #820, since we will already be doing so for dropdowns.

**Comment by AlexKVal** [comment]
Then I mark as 
- [x] `NavBar`'s `navExpanded`-property

and then this issue is done.

--
It seems we need to create another issue for
> navExpanded we should just use uncontrollable

Isn't it ?

**Comment by taion** [comment]
I think it's covered by #820.

**Comment by AlexKVal** [comment]
Ok
